### PR TITLE
Update Microprofile parent version to 2.11

### PR DESCRIPTION
**Pull request by cescoffier**

### CODE REVIEW

**Comment by cescoffier** [comment]
@Emily-Jiang do you think we can get this PR in and a release shortly after that? 

It's just a parent update as the dependencies from the used parents are kind of old.

**Comment by Azquelt** [comment]
Is the goal of this to require Java 11 and EE10 dependencies? If not and we just want the latest dependencies then we should update to the latest 2.x instead.

**Comment by cescoffier** [comment]
Ah I didn't know that. My goal is to get a more recent Arquillian, and about the dependency on Maven Core 3.6.0

**Review by rsvoboda — CHANGES_REQUESTED** [review]
`<version.microprofile.tck.bom>2.8</version.microprofile.tck.bom>` should also change to 3.4 (o version that's picked because of Jakarta comment above)

**Comment by rsvoboda** [comment]
> Is the goal of this to require Java 11 and EE10? If not and we just want the latest plugin and other library dependencies then we should update to the latest 2.x instead.

That would mean https://mvnrepository.com/artifact/org.eclipse.microprofile/microprofile-parent/2.11 correct @Azquelt

**Comment by Azquelt** [comment]
Yes, 2.11 is correct, and you're also right about updating the TCK BOM.

**Comment by cescoffier** [comment]
I've updated the parent and the TCK BOM to 2.11.

**Comment by Azquelt** [comment]
@eclipse-microprofile-bot test this please

**Review by Azquelt — APPROVED** [review]
Output of the PR build looks good (checked formatting and images in the pdf doc and images in the Javadoc).

Updating either the Java version or the parent pom has updated the Javadoc template used for the API docs, but I don't see that as an issue.

**Comment by Emily-Jiang** [comment]
@cescoffier do you need a service release on this? If yes, I don't think it is going to be a problem.

**Comment by cescoffier** [comment]
@Emily-Jiang That would be awesome! Thanks!

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang That would be awesome! Thanks!

Is this the fix you need? If so, we can do a service release next week.

**Comment by cescoffier** [comment]
Yes, I just need this one.

**Pull request merged**
