### PR TITLE
Allow the ScheduledExecutorService to be provided by the container

### PR DESCRIPTION
**Pull request by tevans78**
When running in an Jakarta EE web/full profile environment, the ScheduleExecutorService should be provided by the container.

### CODE REVIEW

**Comment by tevans78** [comment]
@eclipse-microprofile-bot test this please

**Comment by tevans78** [comment]
@eclipse-microprofile-bot test this please

**Comment by Azquelt** [comment]
@eclipse-microprofile-bot test this please

**Comment by tevans78** [comment]
@Azquelt any idea why that build failed?

**Comment by Azquelt** [comment]
```
[ERROR] Failed to execute goal net.revelc.code:impsort-maven-plugin:1.4.1:sort (sort-imports) on project microprofile-reactive-streams-operators-api: Execution sort-imports of goal net.revelc.code:impsort-maven-plugin:1.4.1:sort failed: A required class was missing while executing net.revelc.code:impsort-maven-plugin:1.4.1:sort: null
```

IIRC this is an issue with newer versions of maven and we maybe need to update to a newer version of the MP Parent POM. I'll have a look tomorrow and see if I can sort it out.

**Comment by Azquelt** [comment]
On further investigation, it looks like we updated the versions of Maven and Java in the build in order to allow the update of the parent pom in #177.

If we get that merged, I expect this PR will then build correctly.

**Review by Azquelt — APPROVED** [review]

**Pull request merged**
